version: '3.7'
services:
  httpd:
    image: httpd:2.4-alpine
    ports:
      - "127.0.0.1:8080:80"
    volumes:
      - type: bind
        source: ./projects
        target: /var/www
        consistency: cached
      - ./conf/httpd/httpd.conf:/usr/local/apache2/conf/httpd.conf
    networks:
      - mynetwork
  php:
    image: xoxoxo/php-container
    volumes:
      - type: bind
        source: ./projects
        target: /var/www
        consistency: cached
    networks:
      - mynetwork
  mysql:
    image: leafney/alpine-mariadb
    ports:
      - "127.0.0.1:3306:3306"
    volumes:
      - type: volume
        target: /var/lib/mysql
    networks:
      - mynetwork
    env_file:
      - conf/mysql/credentials.env
networks:
  mynetwork:
